### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by thangnd85** [jaanonim/Voice-Assistant#1]
Can  you explain how to use it? As client an server side.

**Comment by jaanonim** [comment]
Some commands should be executed on a different machine. Therefore each command has a target attribute and (machine name). In `settings.json` (it's in gitingnor so you can see it but you have example file: `settings.example.json`) you define the name of the machine and whether a copy of this code will act as server or client.

**Comment by thangnd85** [comment]
Thank. First time try, i guest that client can use speech recognizer then send it to server process,.
Example I can install server app on a PC, and client on small sbc like Raspberry Pi Zero. 
But this one is different.
